name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  unit-test:
    name: Unit Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ['bruno-js', 'bruno-cli', 'bruno-query', 'bruno-lang', 'bruno-schema', 'bruno-app', 'bruno-common', 'bruno-electron']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # build libraries
      - name: Build libraries
        run: |
          npm run build --workspace=packages/bruno-common
          npm run build --workspace=packages/bruno-query
          npm run sandbox:bundle-libraries --workspace=packages/bruno-js

      # tests
      - name: Test Package ${{ matrix.package }}
        run: npm run test --workspace=packages/${{ matrix.package }}

      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: packages/*/jest/results.xml
          comment_mode: always

      - name: Publish Coverage Report
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          format: cobertura
          flag-name: run-${{ join(matrix.*, '-') }}
          parallel: true

  finish:
    needs: unit-test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        parallel-finished: true

  cli-test:
    name: CLI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build Libraries
        run: |
          npm run build --workspace=packages/bruno-query
          npm run build --workspace=packages/bruno-common
          npm run sandbox:bundle-libraries --workspace=packages/bruno-js

      - name: Run tests
        run: |
          cd packages/bruno-tests/collection
          npm install
          node ../../bruno-cli/bin/bru.js run --env Prod --output junit.xml --format junit

      - name: Publish Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: packages/bruno-tests/collection/junit.xml
          comment_mode: always
